config/routes.rb
Rails.application.routes.draw do
  resource :videos do
    collection do
      post :remove
    end
  end
  resource :articles do
    collection do
      post :remove
    end
  end
  resource :wechat, only: [:show, :create]  do
    collection do
      get :message_box
      get :direct_message_box
    end
  end
  resource :results do
    collection do
      get :videos
      get :articles
      get :t_articles
      get :my_videos
      post :submit_download
      post :submit_article_fav
    end
  end
  resource :wechat_reports do
    collection do
      post :search_result
      post :scholar_result
      post :video_download_result
    end
  end
  namespace :api do
    resources :messages do
      collection do
        post :get_message
      end
    end
  end

  match '*path' => 'errors#error_404', via: :all

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  protect_from_forgery with: :null_session

  def videos
    spyder_id = params[:spyder_id]
    res = HTTParty.get "http://139.162.101.250/api/spyder_videos/videos?spyder_id=#{spyder_id}"
    @data = JSON.parse(res.body)["data"]["videos"]
    @keyword = JSON.parse(res.body)["data"]["keyword"]

    respond_to do |format|
      format.html
    end
  end

  def articles
    spyder_id = params[:spyder_id]
    res = HTTParty.get "http://139.162.101.250/api/spyder_articles/articles?spyder_id=#{spyder_id}"
    @data = JSON.parse(res.body)["data"]["articles"]
    @keyword = JSON.parse(res.body)["data"]["keyword"]

    respond_to do |format|
      format.html
    end
  end

  def t_articles
    spyder_id = params[:spyder_id]
    res = HTTParty.get "http://139.162.101.250/api/spyder_articles/articles?spyder_id=#{spyder_id}"
    @data = JSON.parse(res.body)["data"]["articles"]
    @keyword = JSON.parse(res.body)["data"]["keyword"]

    respond_to do |format|
      format.html
    end
  end

  def my_videos
    user = User.find_or_create_by(open_id: params[:user])
    @videos = user.videos.order(created_at: :desc)

    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def submit_download
    ids = params[:ids].map{|i| i.to_i}
    if (ids && !ids.empty?)
      message = Message.last
      message.delay(:queue => 'sending').video_download(ids)

      render_json(0, '提交成功')
    else
      render_json(1, '提交失败')
    end
  end

  def submit_article_fav
    ids = params[:ids].map{|i| i.to_i}
    if (ids && !ids.empty?)
      message = Message.last
      message.delay(:queue => 'sending').article_collect(ids)

      render_json(0, '提交成功')
    else
      render_json(1, '提交失败')
    end
  end

end

app/helpers/results_helper.rb
module ResultsHelper
  
end

app/views/results/articles.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <title>学术文章搜索结果</title>
        <!-- 引入 WeUI -->
        <!-- <link rel="stylesheet" href="path/to/weui/dist/style/weui.min.css"/> -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-weui/1.1.2/css/jquery-weui.min.css">
    </head>
    <body>
        <div class="weui-cells__title">关键词: <%= @keyword %></div>
        <div class="weui-cells weui-cells_radio">
        <% @data.each do |d| %>
        <a href="<%= d["url"] %>" class="weui-cell weui-check__label">
          <div class="weui-cell__bd">
            <p style="color:#000000;"><%= d["title"] %></p></br>
            <p style="color:#818181;font-size: 16px;"><%= d["summary"] %></p></br>
            <p style="color:#999999;font-size: 15px;">作者:<%= d["author"] %></p>
          </div>
        </a>
        <% end %>
        </div>

      <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script>

    </body>
</html>

app/views/results/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <title>视频搜索结果</title>
        <!-- 引入 WeUI -->
        <!-- <link rel="stylesheet" href="path/to/weui/dist/style/weui.min.css"/> -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-weui/1.1.2/css/jquery-weui.min.css">
        <!-- <link rel="stylesheet" href="http://jqweui.com/dist/demos/css/demos.css"> -->
    </head>
    <body>
      <div id="body">
      <header style="padding: 35px 0;">
        <h1 style="text-align: center;font-size: 34px;color: #3cc51f;font-weight: 400;margin: 0 15%;">图标</h1>
      </header>
      <div style="padding: 15px;">
        <div class="icon-box">
          <i class="weui-icon-success weui-icon_msg"></i>
          <div class="icon-box__ctn">
            <h3 class="icon-box__title">成功1</h3>
            <p class="icon-box__desc">用于表示操作顺利达成</p>
          </div>
        </div>
      </div>
      <div class="weui-footer">
        <p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p>
      </div>
      </div>
      <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script>
    </body>
</html>

app/views/results/my_videos.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <title>视频收藏</title>
        <!-- 引入 WeUI -->
        <!-- <link rel="stylesheet" href="path/to/weui/dist/style/weui.min.css"/> -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-weui/1.1.2/css/jquery-weui.min.css">
    </head>
    <body>
        <div class="weui-cells__title">视频列表</div>
        <div class="weui-cells">
        <% if @videos.empty? %>
        <div style="padding: 15px;">
          <div style="margin-bottom: 25px;display: -webkit-box;display: -webkit-flex;display: flex;-webkit-box-align: center;-webkit-align-items: center;align-items: center">
            <i class="weui-icon-info weui-icon_msg" style="margin-right: 18px"></i>
            <div style="-webkit-flex-shrink: 100;flex-shrink: 100">
              <h3 style="font-weight: 400">您还没有收藏的视频</h3>
              <p style="margin-top: 6px;font-size: 12px;color: #888">请通过对话框搜索后点击“下载”收藏视频</p>
            </div>
          </div>
        </div>
        <% else %>
        <% @videos.each do |v| %>
        <div class="weui-cell weui-cell_swiped" id="cell-<%=v.id%>">
        <div class="weui-cell__bd" style="transform: translate3d(0px, 0px, 0px);">
          <div class="weui-cell">
            <div class="weui-cell__hd"><a href="<%= v.video_src %>"><img src="<%= v.video_cover %>" style="width:144px;margin-right:5px;display:block"></a></div>
            <div class="weui-cell__bd">
              <p><a style="color:#818181;font-size: 15px;" href="<%= v.video_src %>"><%= v.name %></a></p>
            </div>
          </div>
        </div>
        <div class="weui-cell__ft">
          <a class="weui-swiped-btn weui-swiped-btn_warn delete-swipeout" href="javascript:void(0);" id="<%=v.id%>">删除</a>
           <!-- link_to "删除", videos_path(v.id), :method => :delete, :class => "weui-swiped-btn weui-swiped-btn_warn delete-swipeout", :data => { :confirm => '确认删除该视频?'  -->
        </div>
        </div>
        <% end %>
        <% end %>
        </div>
        <div class="weui-footer_fixed-bottom">
          <p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p>
        </div>

        <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
        <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script>
        <script>
        $(document).ready(function() {
          $('.weui-swiped-btn.weui-swiped-btn_warn.delete-swipeout').click(function(event){
            id = this.id
            $.ajax({
                    type: "POST",
                    url: "/videos/remove",
                    data: JSON.stringify( { video_id: id } ),
                    contentType: "application/json",
                    complete: function(){
                      $.toptip('已删除', 2000, 'success');
                      $('#cell-' + String(id)).remove();
                      // $.toast("已删除", 4000);
                    }
                });
            event.preventDefault();
          });
        })

      </script>

    </body>
</html>

app/views/results/show.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <title>视频搜索结果</title>
        <!-- 引入 WeUI -->
        <!-- <link rel="stylesheet" href="path/to/weui/dist/style/weui.min.css"/> -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/weui/1.1.2/style/weui.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-weui/1.1.2/css/jquery-weui.css">
        <!-- <link rel="stylesheet" href="http://jqweui.com/dist/demos/css/demos.css"> -->
    </head>
    <body>
      <div id="body">
      <header style="padding: 35px 0;">
        <h1 style="text-align: center;font-size: 34px;color: #3cc51f;font-weight: 400;margin: 0 15%;">图标</h1>
      </header>
      <div style="padding: 15px;">
        <div style="margin-bottom: 25px;display: -webkit-box;display: -webkit-flex;display: flex;-webkit-box-align: center;-webkit-align-items: center;align-items: center">
          <i class="weui-icon-success weui-icon_msg" style="margin-right: 18px"></i>
          <div style="-webkit-flex-shrink: 100;flex-shrink: 100">
            <h3 style="font-weight: 400">成功</h3>
            <p style="margin-top: 6px;font-size: 12px;color: #888">用于表示操作顺利达成</p>
          </div>
        </div>
      </div>
      <div class="weui-footer">
        <p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p>
      </div>
      </div>
      <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script>
    </body>
</html>

app/views/results/t_articles.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <title>学术文章搜索结果</title>
        <!-- 引入 WeUI -->
        <!-- <link rel="stylesheet" href="path/to/weui/dist/style/weui.min.css"/> -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-weui/1.1.2/css/jquery-weui.min.css">
        <style>.weui-footer_fixed-bottom{bottom: 0; border-radius: 0; z-index: 100;} .weui-btn{border-radius:0} #body{margin-bottom: 50px;}</style>
    </head>
    <body>
      <div id="body">
        <div class="weui-cells__title">关键词: <%= @keyword %></div>
        <div class="weui-cells weui-cells_checkbox">
        <% @data.each do |d| %>
        <label class="weui-cell weui-check__label" for="<%= d["id"] %>">
          <div class="weui-cell__hd">
            <input type="checkbox" class="weui-check" name="checkbox1" id="<%= d["id"] %>" value="<%= d["id"] %>">
            <i class="weui-icon-checked"></i>
          </div>
          <div class="weui-cell__bd">
            <p style="color:#000000;"><%= d["title"] %></p></br>
            <% if !d["summary"].blank? %>
            <p style="color:#818181;font-size: 16px;"><%= d["summary"] %></p></br>
            <% end %>
            <p style="color:#999999;font-size: 15px;">作者:<%= d["author"] %></p>
          </div>
        </label>
        <% end %>
        </div>
        <div class="weui-footer_fixed-bottom">
          <!-- <p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p> -->
          <p class="weui-footer__links">
            <a href="javascript:void(0);" class="weui-btn weui-btn_primary" id="submit">
              收藏
            </a>
          </p>
        </div>
      </div>

      <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script>
      <script>
      $(document).ready(function() {
        $('#submit').click(function(){
        var allVals = [];
          $('input:checkbox:checked').each(function() {
               allVals.push(parseInt($(this).val()));
             });
             if (jQuery.isEmptyObject(allVals)) {
              // $.toast("请选择需要下载的内容", 4000);
              $.toptip('请选择需要收藏的内容', 4000, 'warning');
              return;
             }
            $.ajax
            ({
                url: 'http://wendao.easybird.cn/results/submit_article_fav',
                data: {"ids": allVals},
                type: 'post',
                success: function(result)
                {
                  // $.toast("操作成功", 4000);
                  $.toptip('操作成功', 2000, 'success');
                  setTimeout(
                    function()
                    {
                      $("#body").html('<header style="padding: 35px 0;">' +
                        '<h1 style="text-align: center;font-size: 34px;color: #3cc51f;font-weight: 400;margin: 0 15%;">君悦闻道提示</h1>' +
                      '</header>' +
                      '<div style="padding: 15px;">' +
                        '<div style="margin-bottom: 25px;display: -webkit-box;display: -webkit-flex;display: flex;-webkit-box-align: center;-webkit-align-items: center;align-items: center">' +
                          '<i class="weui-icon-success weui-icon_msg" style="margin-right: 18px"></i>' +
                          '<div style="-webkit-flex-shrink: 100;flex-shrink: 100">' +
                            '<h3 style="font-weight: 400">学术文章收藏成功</h3>' +
                            '<p style="margin-top: 6px;font-size: 12px;color: #888">请到我的收藏中查看</p>' +
                          '</div>' +
                        '</div>' +
                      '</div>' +
                      '<div class="weui-footer_fixed-bottom">' +
                        '<p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p>' +
                      '</div>');
                    }, 2000);
                }
            });
        });
      })

      </script>
    </body>
</html>

app/views/results/videos.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
        <title>视频搜索结果</title>
        <!-- 引入 WeUI -->
        <!-- <link rel="stylesheet" href="path/to/weui/dist/style/weui.min.css"/> -->
        <link rel="stylesheet" href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css">
        <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-weui/1.1.2/css/jquery-weui.min.css">
        <style>.weui-footer_fixed-bottom{bottom: 0; border-radius: 0; z-index: 100;} .weui-btn{border-radius:0} #body{margin-bottom: 50px;}</style>
    </head>
    <body>
      <div id="body">
        <div class="weui-cells__title">关键词: <%= @keyword %></div>
        <div class="weui-cells weui-cells_checkbox">
        <% @data.each do |d| %>
        <label class="weui-cell weui-check__label" for="<%= d["id"] %>">
          <div class="weui-cell__hd">
            <input type="checkbox" class="weui-check" name="checkbox1" id="<%= d["id"] %>" value="<%= d["id"] %>">
            <i class="weui-icon-checked"></i>
          </div>
          <div class="weui-cell__bd">
            <p><%= d["name"] %></p></br>
            <p style="color:#999999;font-size: 15px;">作者:<%= d["author"] %></p>
          </div>
        </label>
        <% end %>
        </div>
        <div class="weui-footer_fixed-bottom">
          <!-- <p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p> -->
          <p class="weui-footer__links">
            <a href="javascript:void(0);" class="weui-btn weui-btn_primary" id="submit">
              下载选中视频
            </a>
          </p>
        </div>
      </div>

      <script src="https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://cdn.bootcss.com/jquery-weui/1.1.2/js/jquery-weui.min.js"></script>
      <script>
      $(document).ready(function() {
        $('#submit').click(function(){
        var allVals = [];
          $('input:checkbox:checked').each(function() {
               allVals.push(parseInt($(this).val()));
             });
             if (jQuery.isEmptyObject(allVals)) {
              // $.toast("请选择需要下载的内容", 4000);
              $.toptip('请选择需要下载的内容', 4000, 'warning');
              return;
             }
            $.ajax
            ({
                url: 'http://wendao.easybird.cn/results/submit_download',
                data: {"ids": allVals},
                type: 'post',
                success: function(result)
                {
                  // $.toast("操作成功", 4000);
                  $.toptip('操作成功', 2000, 'success');
                  setTimeout(
                    function()
                    {
                      $("#body").html('<header style="padding: 35px 0;">' +
                        '<h1 style="text-align: center;font-size: 34px;color: #3cc51f;font-weight: 400;margin: 0 15%;">君悦闻道提示</h1>' +
                      '</header>' +
                      '<div style="padding: 15px;">' +
                        '<div style="margin-bottom: 25px;display: -webkit-box;display: -webkit-flex;display: flex;-webkit-box-align: center;-webkit-align-items: center;align-items: center">' +
                          '<i class="weui-icon-success weui-icon_msg" style="margin-right: 18px"></i>' +
                          '<div style="-webkit-flex-shrink: 100;flex-shrink: 100">' +
                            '<h3 style="font-weight: 400">视频收藏成功</h3>' +
                            '<p style="margin-top: 6px;font-size: 12px;color: #888">正在为您下载,请等待系统消息提示</p>' +
                          '</div>' +
                        '</div>' +
                      '</div>' +
                      '<div class="weui-footer_fixed-bottom">' +
                        '<p class="weui-footer__text">Copyright © 2011-2018 君悦闻道</p>' +
                      '</div>');
                    }, 2000);
                }
            });
        });
      })

      </script>
    </body>
</html>